version: 2.1
jobs:
  build:
    docker:
      # Use this New Image for Starting things up
      - image: fr3akyphantom/droid-runner:latest # DO Not Change
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.1.0'
      USE_SECRET_BOOTABLE: 'true'
      SECRET_BR: 'android-9.0'
      MAINTAINER: 'PBRP Team'
      VENDOR: 'cherry_mobile'
      CODENAME: 'x930'
      BUILD_LUNCH: 'omni_Flare_S8-eng'
      FLAVOR: "eng"
      TEST_BUILD: 'true'
      #EXTRA_CMD: "rm -rf build/soong && git clone https://github.com/PitchBlackRecoveryProject/android_build_soong -b android-10-fixes build/soong && rm -rf vendor/pb && git clone https://github.com/PitchBlackRecoveryProject/vendor_pb -b pb-10.0 vendor/pb"
      CHANGELOG: |
         Initial Test Build
    working_directory: /home/builder/
    steps:
      - setup_remote_docker:
          version: 19.03.8
      - run:
          name: "ALL IN REMOTE"
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
            echo "Ready to Deploy"
            mkdir upload
            export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
            cp out/target/product/${CODENAME}/recovery.img upload/PBRP-${version}-${CODENAME}-$nowTime-Unofficial.img
            cp out/target/product/${CODENAME}/*.img upload/
            cp out/target/product/${CODENAME}/*.zip upload/
            cp out/target/product/${CODENAME}/ramdisk* upload/
            ls -lA upload/
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n "Latest PBRP Release for $(echo $CODENAME)" -b "PBRP $(echo $version)" -delete twrp_v${version} upload/
workflows:
  version: 2
  remote_builder:
    jobs:
      - build:
          filters:
            branches:
              only: 'pbrp-9.0'
          context: org-global
